### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by ondrej-fabry**

### CODE REVIEW

**Comment by TrueFurby** [comment]
@chrismetz09 please see here: https://deploy-preview-8--ligato.netlify.com/ 

I did not remove Blog.. It was commented out. You moved it and left old one as comment. No need to comment out anything we have git for that.

**Comment by chrismetz09** [comment]
okay got it - was using for testing. I'll refrain from that practice where possible. So okay to merge PR. Shall I handle?

**Comment by TrueFurby** [comment]
Sure.

**Comment by chrismetz09** [comment]
cool. then I do pull and start hacking

**Pull request merged**
